### ISSUE TITLE
ZeroDivisionError: float division when validation

### ISSUE THREAD

**Issue by BuiNgocHai** [zzzxxxttt/pytorch_simple_CenterNet_47#2]
First Thanks for your work. and i try to change number class and train my own data, everything is ok when i train but when it run in validation have some error like this 
```2020-08-04 14:26:31.306930 Val@Epoch: 2 [2020-08-04 14:26:31,306]                                                                                     
Traceback (most recent call last):                                                                                                                    
  File "train.py", line 237, in <module>                                                                                                              
    main()
  File "train.py", line 228, in main
    val_map(epoch)
  File "train.py", line 205, in val_map
    soft_nms_merge(results[img_id][j + 1], Nt=0.5, method=2, weight_exp=10)
  File "nms.pyx", line 280, in nms.soft_nms_merge
ZeroDivisionError: float division
```
In nms.pyx I see ``` boxes[i, 0] = mx1 / mts``` and ```mts = boxes[i, 5]```  but some time my ```boxes =[]```, have something wrong in here?

**Comment by zzzxxxttt** [comment]
It's because sometimes the model can't detect any object from the image, just add an "if ..." to skip nms for such images.

**Comment by BuiNgocHai** [comment]
Nice, thank you for your help :+1:
