### ISSUE TITLE
Can not load checkpoint.h7 

### ISSUE THREAD

**Issue by BuiNgocHai** [zzzxxxttt/pytorch_simple_CenterNet_47#4]
I trained my own model and save it to checkpoint.h7 but when i try to load it i had problem like this: 
```Traceback (most recent call last):                                                                                                          [146/1990]
  File "demo.py", line 173, in <module>                                                                                                               
    main()                                                                                                                                            
  File "demo.py", line 79, in main                                                                                                                    
    model.load_state_dict(torch.load(cfg.pretrain_dir))                                                                                               
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict                                              
    self.__class__.__name__, "\n\t".join(error_msgs)))                                                                                                
RuntimeError: Error(s) in loading state_dict for exkp:                                                                                                
        Unexpected key(s) in state_dict: "kps.1.top.0.conv1.weight", "kps.1.top.0.bn1.weight", "kps.1.top.0.bn1.bias", "kps.1.top.0.bn1.running_mean",
 "kps.1.top.0.bn1.running_var", "kps.1.top.0.bn1.num_batches_tracked", "kps.1.top.0.conv2.weight", "kps.1.top.0.bn2.weight", "kps.1.top.0.bn2.bias", "
kps.1.top.0.bn2.running_mean", "kps.1.top.0.bn2.running_var", "kps.1.top.0.bn2.num_batches_tracked", "kps.1.top.1.conv1.weight", "kps.1.top.1.bn1.weig
ht", "kps.1.top.1.bn1.bias", "kps.1.top.1.bn1.running_mean", "kps.1.top.1.bn1.running_var", "kps.1.top.1.bn1.num_batches_tracked", "kps.1.top.1.conv2.
weight", "kps.1.top.1.bn2.weight", "kps.1.top.1.bn2.bias", "kps.1.top.1.bn2.running_mean", "kps.1.top.1.bn2.running_var", "kps.1.top.1.bn2.num_batches
_tracked", "kps.1.low1.0.conv1.weight", "kps.1.low1.0.bn1.weight", "kps.1.low1.0.bn1.bias", "kps.1.low1.0.bn1.running_mean", "kps.1.low1.0.bn1.running
_var", "kps.1.low1.0.bn1.num_batches_tracked", "kps.1.low1.0.conv2.weight", "kps.1.low1.0.bn2.weight", "kps.1.low1.0.bn2.bias", "kps.1.low1.0.bn2.runn
ing_mean", "kps.1.low1.0.bn2.running_var", "kps.1.low1.0.bn2.num_batches_tracked", "kps.1.low1.0.skip.0.weight", "kps.1.low1.0.skip.1.weight", "kps.1.
low1.0.skip.1.bias", "kps.1.low1.0.skip.1.running_mean", "kps.1.low1.0.skip.1.running_var", "kps.1.low1.0.skip.1.num_batches_tracked", "kps.1.low1.1.c
onv1.weight", "kps.1.low1.1.bn1.weight", "kps.1.low1.1.bn1.bias", "kps.1.low1.1.bn1.running_mean", "kps.1.low1.1.bn1.running_var", "kps.1.low1.1.bn1.n
um_batches_tracked", "kps.1.low1.1.conv2.weight", "kps.1.low1.1.bn2.weight", "kps.1.low1.1.bn2.bias", "kps.1.low1.1.bn2.running_mean", "kps.1.low1.1.b
n2.running_var", "kps.1.low1.1.bn2.num_batches_tracked", "kps.1.low2.top.0.conv1.weight", "kps.1.low2.top.0.bn1.weight", "kps.1.low2.top.0.bn1.bias", 
"kps.1.low2.top.0.bn1.running_mean", "kps.1.low2.top.0.bn1.running_var", "kps.1.low2.top.0.bn1.num_batches_tracked", "kps.1.low2.top.0.conv2.weight",
"kps.1.low2.top.0.bn2.weight", "kps.1.low2.top.0.bn2.bias", "kps.1.low2.top.0.bn2.running_mean", "kps.1.low2.top.0.bn2.running_var", "kps.1.low2.top.0
.bn2.num_batches_tracked", "kps.1.low2.top.1.conv1.weight", "kps.1.low2.top.1.bn1.weight", "kps.1.low2.top.1.bn1.bias", "kps.1.low2.top.1.bn1.running_
mean", "kps.1.low2.top.1.bn1.running_var", "kps.1.low2.top.1.bn1.num_batches_tracked", "kps.1.low2.top.1.conv2.weight", "kps.1.low2.top.1.bn2.weight",
 "kps.1.low2.top.1.bn2.bias", "kps.1.low2.top.1.bn2.running_mean", "kps.1.low2.top.1.bn2.running_var", "kps.1.low2.top.1.bn2.num_batches_tracked", "kp
s.1.low2.low1.0.conv1.weight", "kps.1.low2.low1.0.bn1.weight", "kps.1.low2.low1.0.bn1.bias", "kps.1.low2.low1.0.bn1.running_mean", "kps.1.low2.low1.0.
bn1.running_var", "kps.1.low2.low1.0.bn1.num_batches_tracked", "kps.1.low2.low1.0.conv2.weight", "kps.1.low2.low1.0.bn2.weight", "kps.1.low2.low1.0 ```

**Comment by zzzxxxttt** [comment]
just change 
```model.load_state_dict(torch.load(cfg.pretrain_dir))``` 
to 
```model.module.load_state_dict(torch.load(cfg.pretrain_dir))```

**Comment by BuiNgocHai** [comment]
After change to ```model.module.load_state_dict(torch.load(cfg.pretrain_dir))``` i had this problem
```Creating model... [2020-08-06 10:46:12,459]
./ckpt/sompo_hg_511_ddp/checkpoint.t7 [2020-08-06 10:46:12,459]
Traceback (most recent call last):
  File "demo.py", line 173, in <module>
    main()
  File "demo.py", line 79, in main
    model.module.load_state_dict(torch.load(cfg.pretrain_dir))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'exkp' object has no attribute 'module'
```

**Comment by zzzxxxttt** [comment]
Umm... looks like the model you used for demo is not the same with the pretrained model.

**Comment by BuiNgocHai** [comment]
Yeah, I just modify class and trained then I try to load it. So Do I need change another file to make it correct (
do I have to change anything in ```hourglass.py```) ??

**Comment by zzzxxxttt** [comment]
I guess the pretrained model is large_hourglass and the model you used in demo is small_hourglass

**Comment by BuiNgocHai** [comment]
hmm... i think it's not a problem, i tried ```large, tiny, small``` but same error

**Comment by BuiNgocHai** [comment]
That is the problem. thanks for your help
